#!/usr/bin/env bash

# Check if the number of params is less than 4
if [ $# -lt 4 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Transfer the file using scp with disabled strict host key checking
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/
