#!/usr/bin/env bash
# Install nginx and configure it on a remote server

apt-get -y update
apt-get install -y nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello world!" > /var/www/html/index.html
service nginx restart
