#!/usr/bin/env bash
# Read the /etc/passwd file line by line

while IFS=: read -r username _ uid _ _ home shell; do
    echo "The user $username is part of the $uid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: ${uid:-No additional info}"
done < /etc/passwd
